package tokenizer;

public enum TokenType {
	VAR, CONST, STRING_CONST, KEY_WORD, DATA_TYPE, OPERATOR, HIGHEST_PRIORITY_OPERATOR, HIGH_PRIORITY_OPERATOR, MEDIUM_PRIORITY_OPERATOR
	,LOW_PRIORITY_OPERATOR,COMPARISON_OPERATOR, BODY, OPERATOR_OR, OPERATOR_AND, OPERATOR_NOT, CONDITION
}
