package tokenizer;

public enum TokenType {
	VAR, CONST, STRING_CONST, KEY_WORD, DATA_TYPE, HIGHEST_PRIORITY_OPERATOR, HIGH_PRIORITY_OPERATOR, MEDIUM_PRIORITY_OPERATOR,
	LOW_PRIORITY_OPERATOR, COMPARISON_OPERATOR, BODY,LOGICAL_OPERATOR , CONDITION, FUNCTION_CALL, IF, WHILE, FOR,
	FUNC, L_BRACKET, R_BR, COMMA, DOT, L_BR, R_BRACKET, SEMICOLON, NOT, OR, EQUAL, AND, EQUALS, NEQUALS, LT, GT, LET, GET, SUM, INC, DEC,
	SUBTRACTION, L_INDEX_OPERATOR, DIVIDE, R_INDEX_OPERATOR, SUM_EQ, SUB_EQ, LONG, BOOL, DOUBLE, STRING, LIST, MUL, ELSE, RETURN, OPERATOR;
}
